name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: pnpm run build

      - name: Archive artifact
        run: |
          tar --dereference --hard-dereference -cvf artifact.tar dist/*
        working-directory: ${{ github.workspace }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: "github-pages"
          path: artifact.tar
